spring.mail.host=live.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=api
spring.mail.password=a5e2563bddd9cdca22ecf736c3e332fc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.attachment.file.path=test
spring.mail.to.address=xxx@gmail.com
