spring:
  application:
    name: spring-ai

  ai:
    google:
      genai:
        chat:
          options:
            model: gemini-2.5-flash
        embedding:
          text:
            model: gemini-embedding-001

server:
  port: 8080

logging:
  level:
    org.springframework.ai: DEBUG
